export const POSTGRES_USER = process.env.POSTGRES_USER || "postgres"
export const POSTGRES_PASSWORD = process.env.POSTGRES_PASSWORD || "postgres"
export const POSTGRES_DB = process.env.POSTGRES_DB || "postgres"
export const POSTGRES_HOST = process.env.POSTGRES_HOST || "localhost"
export const POSTGRES_PORT = process.env.POSTGRES_PORT || "5432"
